In [1]:
import sys
sys.path.append('..')
from osp import *

df_meta = get_corpus_metadata()
worddb = get_worddb().fillna('')
ok_words = {word for word in worddb.index}

In [2]:
df_meta.discipline.value_counts()

discipline
Philosophy    32277
Other         32277
Literature    25343
Name: count, dtype: int64

In [3]:
stash = STASH_SLICES
stash

LMDBHashStash(~/github/ordinary-style-philosophy/data/raw/stash/osp_slices_1000/lmdb.hashstash.lz4+b64/data.db)

In [4]:
def tokenize_agnostic(txt: str):
    """Tokenize text in a language-agnostic way.

    Args:
        txt: The input text.

    Returns:
        A list of tokens.
    """
    return re.findall(r"[\w']+|[.,!?; -—–'\n]", txt)

tokenize_agnostic("Hello, world!")

['Hello', ',', ' ', 'world', '!']

In [5]:
# def iter_corpus_txt_slices(slice_len=10):
#     num_recog = 0
#     slicex = []
#     for id, txt in iter_corpus_txt():
#         num_slices = 0
#         for si,sent in enumerate(txt.strip().split('\n')):
#             for word in tokenize_agnostic(sent):
#                 if word.strip() and word.lower() in ok_words:
#                     num_recog += 1
#                 slicex.append(word)
#             if num_recog >= slice_len:
#                 num_slices += 1
#                 otxt = ''.join(slicex).strip()
#                 yield id,num_slices,otxt
#                 slicex = []
#                 num_recog = 0
#             slicex.append('\n')

In [6]:
OK_WORDS = None
def get_ok_words():
    global OK_WORDS
    if OK_WORDS is None:
        worddb = get_worddb().fillna('')
        OK_WORDS = {word for word in worddb.index}
    return OK_WORDS


def iter_txt_slices(txt, slice_len=10, ok_words=None):
    num_recog = 0
    slicex = []
    num_slices = 0
    for si,sent in enumerate(txt.strip().split('\n')):
        for word in tokenize_agnostic(sent):
            if word.strip().isalpha() and word.lower() in ok_words:
                num_recog += 1
            slicex.append(word)
        if num_recog >= slice_len:
            num_slices += 1
            otxt = ''.join(slicex).strip()
            yield num_slices,otxt
            slicex = []
            num_recog = 0
        slicex.append('\n')

In [7]:
df_meta.query('discipline == "Other"').sample(10)

,uuid,title,author,year,journal,volume,issue,url,publisher,discipline,...,decade,period,century,halfcentury,century_discipline,halfcentury_discipline,period_discipline,decade_discipline,century_journal,journal_orig
id,,,,,,,,,,,,,,,,,,,,,
other/10.2307/27045820,63b504e2-a5cb-385c-8f05-5a1c9733c515,"Una digitalización sostenible, inclusiva y justa",Christoph Steck,2018,Política Exterior,32,185,jstor.org/stable/10.2307/27045820,Estudios de Política Exterior S. A.,Other,...,2010,2000-2025,C21,eC21,C21 Other,eC21 Other,2000-2025 Other,2010 Other,C21 Política Exterior,Política Exterior
other/10.2307/20657080,66fa32a1-b83f-3e19-9c46-6ce9282da021,Zum Germanennamen,R. Henning,1920,Zeitschrift für deutsches Altertum und deutsche Literatur,57,3/4,jstor.org/stable/10.2307/20657080,Franz Steiner Verlag; S. Hirzel Verlag,Other,...,1920,1900-1925,C20,eC20,C20 Other,eC20 Other,1900-1925 Other,1920 Other,C20 Zeitschrift für deutsches Altertum und deutsche Literatur,Zeitschrift für deutsches Altertum und deutsche Literatur
other/10.2307/insipent.31.28.17,a878d1c1-7c9e-3625-bb09-29ecf4125ec8,DOD Looking Into Commercial Cyber Ranges To Test Apps,Scott Maucione,2015,Inside the Pentagon,31,28,jstor.org/stable/10.2307/insipent.31.28.17,Inside Washington Publishers,Other,...,2010,2000-2025,C21,eC21,C21 Other,eC21 Other,2000-2025 Other,2010 Other,C21 Inside the Pentagon,Inside the Pentagon
other/10.2307/45048638,41c21dcc-2358-30d2-bb36-a251f31fe944,No,Bruce Jones,2014,The World Today,70,4,jstor.org/stable/10.2307/45048638,Royal Institute of International Affairs,Other,...,2010,2000-2025,C21,eC21,C21 Other,eC21 Other,2000-2025 Other,2010 Other,C21 The World Today,The World Today
other/10.2307/25117094,c276b326-c5a6-3d11-8316-55875f432536,Ellie Mae Leaves in a Hurry,Peter Klappert,1970,The North American Review,255,2,jstor.org/stable/10.2307/25117094,University of Northern Iowa,Other,...,1970,1950-1975,C20,lC20,C20 Other,lC20 Other,1950-1975 Other,1970 Other,C20 The North American Review,The North American Review
other/10.2307/45044533,b9e756ed-8123-3dc0-95a0-944b108f1568,THE SOURCES OF THE OLDEST KNOWN EDITION OF VILLON,Grace Frank,1923,Romania,49,196,jstor.org/stable/10.2307/45044533,Librairie Droz,Other,...,1920,1900-1925,C20,eC20,C20 Other,eC20 Other,1900-1925 Other,1920 Other,C20 Romania,Romania
other/10.2307/27006494,0adacbd7-f3d1-325b-9741-a6ba40263a6d,François N. Diederich,"Kendall N. Houk, J. Fraser Stoddart",2020,Proceedings of the National Academy of Sciences of the United States of America,117,52,jstor.org/stable/10.2307/27006494,National Academy of Sciences,Other,...,2020,2000-2025,C21,eC21,C21 Other,eC21 Other,2000-2025 Other,2020 Other,C21 Proceedings of the National Academy of Sciences of the United States of America,Proceedings of the National Academy of Sciences of the United States of America
other/10.2307/25689028,e7397374-45dd-34e0-9367-8300fa3a6ca6,"$5,000 Grant Made for Terminology Project",Georgia H. Faison,1937,Bulletin of the American Library Association,31,2,jstor.org/stable/10.2307/25689028,American Library Association,Other,...,1930,1925-1950,C20,eC20,C20 Other,eC20 Other,1925-1950 Other,1930 Other,C20 Bulletin of the American Library Association,Bulletin of the American Library Association
other/10.2307/45209161,76fd3e68-bb6c-32e3-bd71-13216459f929,In the Eyes of Uman Pilgrims: A Vision of Place and Its Inhabitants,Alla Marchenko,2018,Contemporary Jewry,38,2,jstor.org/stable/10.2307/45209161,Springer,Other,...,2010,2000-2025,C21,eC21,C21 Other,eC21 Other,2000-2025 Other,2010 Other,C21 Contemporary Jewry,Contemporary Jewry
other/10.2307/45215095,386914ac-9036-38c4-93ac-b41be02f5a81,"'This extract is no good, Miss!' Helping post-16 students to make judgements about an historian's construction of argument",Paula Worth,2018,Teaching History,NaN,170,jstor.org/stable/10.2307/45215095,Historical Association,Other,...,2010,2000-2025,C21,eC21,C21 Other,eC21 Other,2000-2025 Other,2010 Other,C21 Teaching History,Teaching History

In [8]:
get_corpus_txt('other/10.2307/3505734')

"There is considerable debate about whether tropical forests can be managed for timber production and to conserve biodiversity.\nFew 'sustainable forestry' systems have been evaluated adequately in this respect.\nMicrochiropteran bats may be model taxa for this purpose.\nThey are an important component of mammalian diversity, play key roles in forest dynamics and are indicators of disturbance in neotropical forests.\nWe investigated the effect of Trinidad's periodic block system (PBS) on bat species diversity and community organization.\nSelective logging did not affect species diversity but did affect community structure.\nFrugivorous bats were significantly more abundant in logged forest whereas gleaning animalivores were more abundant in primary forest, suggesting that frugivores benefited and gleaning animalivores were adversely affected by logging.\nThe bat community showed evidence of recovery.\nThe number of years since forest disturbance was positively correlated with the abundance and number of species of gleaning animalivores and negatively correlated with the proportional abundance of the most common species.\nGleaning animalivores increased in abundance with forest regeneration, whereas the community became less dominated by a single generalist frugivore.\nSynthesis and applications.\nPBS selective logging appears to be compatible with the conservation of bat diversity.\nThis provides evidence that neotropical forests can be managed for timber production in an ecologically sustainable way and that significant biodiversity conservation efforts can occur outside national parks and nature reserves in areas set aside for sustainable development.\nPBS could serve as a basic blueprint for sustainable forestry in the Guianan Shield where there are forests similar in species composition to those of Trinidad.\nKey attributes that could be adopted by many tropical countries to manage their forests in an ecologically sustainable way are a low intensity harvest, a long rotation and multiple controls on harvesting.\nSome urge that more forest should be included in reserves and protected areas (Bowles et al.\nThe reality is that only a small proportion of tropical forest is adequately protected in national parks and nature reserves, and logging of most of the remaining unprotected forest appears inevitable.\nSustainable exploitation of tropical forests may be the most realistic way of ?\nOnly the most valuable timber is harvested and the forest is then allowed to recover through natural regeneration before the next crop of timber is harvested.\nAlthough there is an increase in 'sustainable forestry' systems throughout the tropics, few have been adequately evaluated with respect to biodiversity conservation.\nThere is growing evidence that bats are good indicators of forest disturbance in neotropical forests (Fenton et al.\nThis, coupled with the roles of bats as dispersers and pollinators, suggests they have a significant effect on forest dynamics and, if forests are to be managed in a sustainable way, it is important that the responses of bats to forest disturbance are understood.\nTrinidad, the larger of the two islands forming the Republic of Trinidad and Tobago, is an ideal locality for examining the impacts of different systems of forest management on biodiversity conservation.\nMost of Trinidad's forests are state owned and legally proclaimed as forest reserves managed primarily for timber production.\nOne of the most important areas for timber production is the Victoria-Mayaro Forest Reserve (VMFR).\nTypically each year one block of forest is logged before being closed to allow forest regeneration.\nTo develop sustainable logging systems it is critical that we understand how the intensity (volume of timber removed), frequency (length of interval between harvests) and method of logging affect wildlife.\nThis information can be used to develop and implement measures to maintain biodiversity.\nWe tested whether the PBS is ecologically sustainable by determining the responses of bats to this harvesting system and investigating whether the bat community recovers with post-logging forest regeneration.\nThe next most dominant canopy species are Carapa guianensis Aublet, Terminalia dichotoma G.\nRainfall is seasonally distributed, with the wet season lasting from June to December and the dry season from January to May.\nForestry is the main land use in south-east Trinidad.\nThe Trinity Hills Wildlife Sanctuary borders the VMFR to the south and the Southern Watershed and Rochard Douglas Forest Reserves to the west.\nThere are no national parks or strict nature reserves primarily dedicated to biodiversity conservation in Trinidad (IUCN categories I and II protected areas; http://www.unep-wcmc.org/protected_areas/data).\nThe protected area network is composed primarily of forest reserves the main function of which is timber ?\nThere are a limited number of wildlife reserves but timber production still takes priority.\nHowever, other than a small area converted to teak Tectona grandis L., timber production in the VMFR is under PBS management.\nMora is the main timber harvested.\nOne or two blocks are opened each year to satisfy local demand from woodworkers and saw millers and logging is confined to the dry season.\nVines and lianas are then cut.\nThere are no girth limits for trees but there are many controls on harvesting.\nFRIM uses ecological criteria to select trees to be harvested.\nWoodworkers and saw millers can only harvest trees that FRIM has selected for felling.\nA harvest of two to four trees per hectare is most common.\nNatural disturbance rates are only available from PBS forest regenerating for several decades.\nOur choice of sites in PBS-managed forest was dictated by the need to control for forest type and disturbance history.\nThe five sites were selected because they were in Mora forest, had been logged only once and were not damaged by fire.\nAs a metric of forest disturbance a spherical densiometer was used to estimate the extent of canopy closure at sampling sites (Forest Densiometers, Bartlesville, OK).\nWood et al.\nNets were positioned to sample all microhabitats present: ridge tops, valley bottoms and streams, flat well-drained ground, swampy areas, under closed canopy or in tree-fall gaps.\nIDensiometer recordings made in the wet season.\nNA, not applicable; UN, data unavailable.\nWe used individually numbered aluminium wing bands to mark bats before they were released at the site of capture.\nThe number of nets or harp traps multiplied by the number of hours they were deployed equalled the number of net hours or harp trap hours.\nHarp trap and mist net samples were used to calculate relative abundance and capture rate (bats net-' h-' and trap-' h-').\nRecaptures were not included in abundance estimates.\nBat taxonomy follows Simmons (in press).\nVoucher specimens were deposited at the University of the West Indies (UWI, St Augustine, Trinidad).\nThe skulls of voucher specimens were later examined and craniodental measurements were taken to confirm taxonomic identification.\nTypically we collected only one or two individuals per species as voucher specimens.\nWe checked mist nets and the harp trap regularly and captures were always placed individually in cloth bags and processed promptly.\nDuring processing, pregnant, lactating and females carrying young were given priority over males and non-reproductive females and typically they were not collected as voucher specimens.\nANALYSES Few inventories approach completion, despite intensive sampling effort.\nAlpha diversity was determined using the log series index (oc).\nThe reciprocal form of the index (lid) is given so that an increase in the value of the index represents an increase in diversity and a reduction in dominance.\nKolmogorovSmirnov two-sample tests were used to compare the species abundance distributions between primary and PBS forest.\nDistributions were examined in relation to four main models: the geometric series, log series, log normal and broken-stick.\nMathematical fit of the data to models was made using chi-square goodness-of-fit tests (x\x7f).\nThe number of species and individuals in guilds was compared using chi-square tests.\nWe used data from primary forest to generate expected values (adopting the hypothesis that logging had no effect).\nBecause of the small sample sizes we did not include omnivores, sanguivores and carnivores in chi-square tests.\nWe used Spearman's rank correlation tests (rs) to analyse the association between forest regeneration (years since forest disturbance) and bat species richness, alpha diversity, proportional abundance of the most common species, number of species and individuals in each guild, and number of rare species.\nSPECIES DIVERSITY Bat species richness was similar among sites in primary forest and forest managed with the PBS.\nSpecies were accumulated at a slightly higher rate in primary forest than logged sites (Fig.\nRank abundance plots of bats of primary forest and forest under PBS management forest in the VMFR.\nThere was no evidence of an association between the number of years that sites have been left to regenerate after logging and similarity to primary forest.\nIncludes bats captured in ground-level and subcanopy mist nets and harp traps.\nPercentage similarity in bat species composition between pairs of forest sites.\nThe next most frequently captured bats were nectarivores, gleaning animalivores and aerial insectivores.\nOmnivores, sanguivores and carnivorous bats were represented by few captures.\nExamination of standardized residuals for chi-square tests indicated that this result was attributable to the large difference between primary and logged forest in the abundance of frugivores and gleaning animalivores.\nArtibeusjamaicensis was not uncommon in logged forest but was rarely captured in primary forest.\nBats in other guilds were represented by too few captures to allow rigorous comparisons.\nDiscussion INVENTORY COMPLETENESS We took care to equalize sampling effort among sites and adopt a standardized sampling protocol utilizing several capture methods to maximize inventory completeness and allow valid quantitative comparisons to be made.\nDespite setting nets in the subcanopy and using harp traps, we probably undersampled non-phyllostomid bats.\nTwentyone per cent of the species recorded were aerial insectivores and most were represented by few captures.\nWe infrequently captured aerial insectivores belonging to the Emballonuridae and Vespertilionidae and did not capture Molossidae.\nIn Trinidad, all molossids, a few vesper bats and a single emballonurid species (Diclidurus albus) forage in the unobstructed airspace outside or above the forest, explaining why they were not recorded.\nFor non-phyllostomid species (aerial insectivores) that forage in the forest interior, but which may remain undetected or under-sampled using mist nets and harp traps, time-expansion bat detectors may prove to be a useful tool in the future.\nThese species include Thyroptera tricolor, Furipterus horrens, Natalus tumidorostris, most emballonurids and all mormoopids.\nBATS AND LOGGING We found gleaning animalivores to be adversely affected by logging.\nThe vulnerability of gleaning animalivores to forest disturbance most probably derives from altered resource distributions and we suggest that a specialized diet may be a key factor.\nLogging operations fragment forests as roads and skid trails are built to extract trees.\nBats may be affected if predation risk or commuting costs increase as they traverse unsuitable matrix habitats.\nGleaning bats typically have more restricted geographical ranges than aerial foragers and may be more at risk of extinction as a result of habitat modification and loss (Arita et al.\nThe nectarivorous Glossophaga soricina appears to be unaffected by logging.\nNone of the bat species we captured appears to be restricted to logged forest.\nIn general we found frugivorous bats to be far more abundant in logged forest, indicating that some species may benefit from changes to the forest brought about by timber extraction.\nOur findings are in agreement with other studies that show that disturbed neotropical forests harbour many more individual bats than undisturbed forests, providing that forest composition and structure remain essentially intact.\nThis is principally a result of an increase in the abundance of a few frugivorous species (Brosset et al.\nThe greater abundance of Carollia perspicillata at most sites in logged forest in the VMFR was probably the result of an increased abundance of Piper and other bat-dispersed pioneer plants.\nOthers have also found Carollia to be more ?\nMost frugivorous phyllostomids are dietary generalists and it is likely that many species may take advantage of an increase in fruit production by pioneer plants in logged forest, even if these fruits do not form the core of their diet.\nIndeed many bats are able to shift their diets partially or adapt their behaviour to compensate for an alteration in the availability of their main food types, perhaps explaining why selective logging is not detrimental to many species.\nThe plasticity in diet, foraging behaviour and high mobility of many frugivorous phyllostomids may make them less vulnerable to localized habitat disturbances than gleaning animalivores.\nNEOTROPICAL BATS AS INDICATORS OF FOREST DISTURBANCE Bats are indicators of disturbance in neotropical forests (Fenton et al.\nWe found that selective logging affects the abundance and species richness of gleaning animalivores and the proportional abundance of the most common (Carolliinae) species.\nGiven the absence of national parks and protected nature reserves in Trinidad, the continued survival of these species and other bats may largely depend on adequate protection of existing forest reserves.\nIndeed throughout the neotropics most forest exists outside national parks and nature reserves, and our study illustrates that significant biodiversity conservation efforts can occur in other types of reserves, such as those set aside for sustainable development.\nHowever, national parks should be established in Trinidad and protection of forest reserves needs to be strengthened against agricultural encroachment, squatting, illegal hunting and wildfires.\nCurrent legislation is inadequate to prevent illegal activities, perpetrators are rarely prosecuted and wardens infrequently patrol forest reserves.\nWe found that PBS management does not appear to affect bat species diversity in Trinidad.\nAlthough PBS management affects bat community structure, we found evidence of community recovery.\nAs the forest regenerates there is an increase in the abundance and number of species of gleaning animalivores, which are the bats most sensitive to forest disturbance and characteristic of mature and undisturbed forest in the neotropics.\nFurthermore, the community appears to become less dominated by Carollia perspicillata, a ubiquitous and generalist frugivore that feeds primarily on the fruits of pioneer plants.\nAerial insectivores were probably undersampled and we cannot predict the effect of PBS management on these species.\nAlthough the bat community shows signs of recovery, at the end of the harvesting rotation the abundance of gleaning animalivores is lower than in primary forest.\nTogether with our findings, studies on epiphytes and forest dynamics suggest that plant and animal communities recover but may not recover fully before a second harvest.\nIt is unrealistic to think that most floral and faunal communities can recover completely over a few decades.\nFurthermore, some species may be lost as a result of the increasing forest homogeneity that occurs over successive harvesting rotations.\nHowever, this potential loss of biodiversity must be put in perspective.\nPressure on Trinidad's forestry base is high and selective logging is competing against more destructive land-use interests that have a much larger impact on biodiversity.\nIn some forest reserves large areas have already been converted to plantations of teak and Caribbean pine Pinus caribaea Morelet.\nPBS is a polycyclic system with a low intensity harvest, and a relatively long harvesting rotation, and these attributes may largely account for the maintenance of bat species diversity.\nIn the VMFR the PBS results in a mosaic of lightly disturbed forest blocks at different stages of succession and unexploited forest.\nThe multiple controls on harvesting with ecological criteria used to select trees to be harvested may further account for the compatibility of the PBS with biodiversity conservation.\nAlthough the length of the harvesting rotation could be extended by several decades to allow greater recovery of floral and faunal communities, this would be unwise if it resulted in logging more primary forest to satisfy the annual demand for timber.\nA reduction in the size of the remaining undisturbed forest may result in a greater loss of biodiversity than would be conserved by lengthening the harvesting rotation.\nAlthough the high mobility of bats and the plasticity in foraging behaviour and diet of many species may allow them to adapt to forest disturbance, species with small home ranges and specialized diets and/or roosting requirements, such as gleaning animalivores, may be especially threatened by disturbance to forests.\nThe survival of some species may require that some undisturbed areas in the VMFR are protected from exploitation.\nUnfortunately, the Forestry Division regards undisturbed forest primarily as a strategic timber reserve.\nWe recommend that it should be not be logged.\nImprovements to the PBS could be made.\nThe PBS is unique to Trinidad and it is unclear whether other countries can easily adopt the system to sustainably manage their forests.\nTimber produced by the PBS is not exported to generate foreign revenue but instead ensures a continuous supply of wood to Trinidad's local market while maintaining forest integrity.\nMoreover, in contrast to most other countries in tropical America, forestry has not needed to be financially autonomous because of heavy state subsidies from Trinidad's gasand oil-rich revenue base.\nFinally, although the PBS is a good example of sustainable timber production, this may partly be because Mora is a single-dominant forest that is floristically simple and regenerates well after logging with little management intervention.\nFor countries with single-dominant forests similar in species composition to those of Trinidad, the PBS could serve as a basic blueprint for sustainable timber production, for example Guyana's Mora and Morabukea forests (ter Steege et al.\nKey attributes of the PBS that other countries could adopt to manage their forests sustainably are a low intensity harvest, a long rotation and comprehensive controls on harvesting overseen by experienced forestry officers.\nHowever, it should be noted that silvicultural systems should not be regarded as packages to be applied to forests about which little is known, and it will be a challenge for individual countries to develop or refine existing systems of sustainable forestry to suit local biotic and socioeconomic conditions.\nThis task is vital, as sustainable management holds the key to conserving the world's biodiversity.\nAcknowledgements This research was funded by a research grant from The Leverhulme Trust, reference no.\nWe thank Ruari Allan, Daveka Boodram, Katherine Fisher, Anita Hogan, Dorothea Pio, Donna Piccini, Gaya Sriskanthan and Ana Pefia Tufias for assistance in fieldwork.\nWe are indebted to Mike Oatham and Sheeba Sreenisivan, University of the West Indies, for PBS data.\nWe thank Nadra Gyan and Krishnna John, Forestry Division, and Petrotrin Ltd for providing accommodation.\nBawa, K.S.\nBeard, J.S.\nClarendon Press, Oxford, UK.\nAnimal Sonar (eds P.E.

In [9]:
get_text_slices('other/10.2307/3505734')

{0: 'There is considerable debate about whether tropical forests can be managed for timber production and to conserve biodiversity Few systems have been evaluated adequately in this respect bats may be model taxa for this purpose They are an important component of mammalian diversity play key roles in forest dynamics and are indicators of disturbance in neotropical forests We investigated the effect of periodic block system on bat species diversity and community organization Selective logging did not affect species diversity but did affect community structure bats were significantly more abundant in logged forest whereas gleaning were more abundant in primary forest suggesting that benefited and gleaning were adversely affected by logging The bat community showed evidence of recovery The number of years since forest disturbance was positively correlated with the abundance and number of species of gleaning and negatively correlated with the proportional abundance of the most common species Gleaning increased in abundance with forest regeneration whereas the community became less dominated by a single generalist Synthesis and applications selective logging appears to be compatible with the conservation of bat diversity This provides evidence that neotropical forests can be managed for timber production in an ecologically sustainable way and that significant biodiversity conservation efforts can occur outside national parks and nature reserves in areas set aside for sustainable development could serve as a basic blueprint for sustainable forestry in the Shield where there are forests similar in species composition to those of Key attributes that could be adopted by many tropical countries to manage their forests in an ecologically sustainable way are a low intensity harvest a long rotation and multiple controls on harvesting Some urge that more forest should be included in reserves and protected areas The reality is that only a small proportion of tropical forest is adequately protected in national parks and nature reserves and logging of most of the remaining unprotected forest appears inevitable Sustainable exploitation of tropical forests may be the most realistic way of Only the most valuable timber is harvested and the forest is then allowed to recover through natural regeneration before the next crop of timber is harvested Although there is an increase in systems throughout the tropics few have been adequately evaluated with respect to biodiversity conservation There is growing evidence that bats are good indicators of forest disturbance in neotropical forests This coupled with the roles of bats as dispersers and pollinators suggests they have a significant effect on forest dynamics and if forests are to be managed in a sustainable way it is important that the responses of bats to forest disturbance are understood the larger of the two islands forming the Republic of and is an ideal locality for examining the impacts of different systems of forest management on biodiversity conservation Most of forests are state owned and legally proclaimed as forest reserves managed primarily for timber production One of the most important areas for timber production is the Forest Reserve Typically each year one block of forest is logged before being closed to allow forest regeneration To develop sustainable logging systems it is critical that we understand how the intensity volume of timber removed frequency length of interval between harvests and method of logging affect wildlife This information can be used to develop and implement measures to maintain biodiversity We tested whether the is ecologically sustainable by determining the responses of bats to this harvesting system and investigating whether the bat community recovers with post logging forest regeneration The next most dominant canopy species are Rainfall is seasonally distributed with the wet season lasting from June to December and the dry season from January to May Forestry is the main land use in The Hills Wildlife Sanctuary borders the to the and the Southern Watershed and Forest Reserves to the There are no national parks or strict nature reserves primarily dedicated to biodiversity conservation in categories and protected areas data The protected area network is composed primarily of forest reserves the main function of which is timber There are a limited number of wildlife reserves but timber production still takes priority However other than a small area converted to teak timber production in the is under management is the main timber harvested One or two blocks are opened each year to satisfy local demand from woodworkers and saw millers and logging is confined to the dry season Vines and lianas are then cut There are no girth limits for trees but there are many controls on harvesting uses ecological criteria to select trees to be harvested Woodworkers and saw millers can only harvest trees that has selected for felling A harvest of two to four trees per hectare is most common Natural disturbance rates are only available from forest regenerating for several decades Our choice of sites in managed forest was dictated by the need to control for forest type and disturbance history The five sites were selected because they were in forest had been logged only once and were not damaged by fire As a metric of forest disturbance a spherical was used to estimate the extent of canopy closure at sampling sites Forest OK Wood Nets were positioned to sample all microhabitats present ridge tops valley bottoms and streams flat well drained ground swampy areas under closed canopy or in tree fall gaps recordings made in the wet season NA not applicable data unavailable We used individually numbered aluminium wing bands to mark bats before they were released at the site of capture The number of nets or harp traps multiplied by the number of hours they were deployed equalled the number of net hours or harp trap hours Harp trap and mist net samples were used to calculate relative abundance and capture rate bats net and trap Recaptures were not included in abundance estimates Bat taxonomy follows in press Voucher specimens were deposited at the University of the The skulls of voucher specimens were later examined and measurements were taken to confirm taxonomic identification Typically',
 1: 'we collected only one or two individuals per species as voucher specimens We checked mist nets and the harp trap regularly and captures were always placed individually in cloth bags and processed promptly During processing pregnant lactating and females carrying young were given priority over males and reproductive females and typically they were not collected as voucher specimens ANALYSES Few inventories approach completion despite intensive sampling effort Alpha diversity was determined using the log series index The reciprocal form of the index lid is given so that an increase in the value of the index represents an increase in diversity and a reduction in dominance two sample tests were used to compare the species abundance distributions between primary and forest Distributions were examined in relation to four main models the geometric series log series log normal and broken stick Mathematical fit of the data to models was made using chi square goodness of fit tests The number of species and individuals in guilds was compared using chi square tests We used data from primary forest to generate expected values adopting the hypothesis that logging had no effect Because of the small sample sizes we did not include omnivores and carnivores in chi square tests We used rank correlation tests to analyse the association between forest regeneration years since forest disturbance and bat species richness alpha diversity proportional abundance of the most common species number of species and individuals in each guild and number of rare species SPECIES DIVERSITY Bat species richness was similar among sites in primary forest and forest managed with the Species were accumulated at a slightly higher rate in primary forest than logged sites Fig Rank abundance plots of bats of primary forest and forest under management forest in the There was no evidence of an association between the number of years that sites have been left to regenerate after logging and similarity to primary forest Includes bats captured in ground level and mist nets and harp traps Percentage similarity in bat species composition between pairs of forest sites The next most frequently captured bats were gleaning and aerial insectivores Omnivores and carnivorous bats were represented by few captures Examination of standardized residuals for chi square tests indicated that this result was attributable to the large difference between primary and logged forest in the abundance of and gleaning was not uncommon in logged forest but was rarely captured in primary forest Bats in other guilds were represented by too few captures to allow rigorous comparisons Discussion INVENTORY COMPLETENESS We took care to equalize sampling effort among sites and adopt a standardized sampling protocol utilizing several capture methods to maximize inventory completeness and allow valid quantitative comparisons to be made Despite setting nets in the and using harp traps we probably bats Twentyone per cent of the species recorded were aerial insectivores and most were represented by few captures We infrequently captured aerial insectivores belonging to the and and did not capture In all a few vesper bats and a single species forage in the unobstructed airspace outside or above the forest explaining why they were not recorded For species aerial insectivores that forage in the forest interior but which may remain undetected or under sampled using mist nets and harp traps time expansion bat detectors may prove to be a useful tool in the future These species include tricolor most and all BATS AND LOGGING We found gleaning to be adversely affected by logging The vulnerability of gleaning to forest disturbance most probably derives from altered resource distributions and we suggest that a specialized diet may be a key factor Logging operations fragment forests as roads and skid trails are built to extract trees Bats may be affected if predation risk or commuting costs increase as they traverse unsuitable matrix habitats Gleaning bats typically have more restricted geographical ranges than aerial foragers and may be more at risk of extinction as a result of habitat modification and loss The appears to be unaffected by logging None of the bat species we captured appears to be restricted to logged forest In general we found bats to be far more abundant in logged forest indicating that some species may benefit from changes to the forest brought about by timber extraction Our findings are in agreement with other studies that show that disturbed neotropical forests harbour many more individual bats than undisturbed forests providing that forest composition and structure remain essentially intact This is principally a result of an increase in the abundance of a few species The greater abundance of at most sites in logged forest in the was probably the result of an increased abundance of Piper and other bat dispersed pioneer plants Others have also found to be more Most are dietary generalists and it is likely that many species may take advantage of an increase in fruit production by pioneer plants in logged forest even if these fruits do not form the core of their diet Indeed many bats are able to shift their diets partially or adapt their behaviour to compensate for an alteration in the availability of their main food types perhaps explaining why selective logging is not detrimental to many species The plasticity in diet foraging behaviour and high mobility of many may make them less vulnerable to localized habitat disturbances than gleaning NEOTROPICAL BATS AS INDICATORS OF FOREST DISTURBANCE Bats are indicators of disturbance in neotropical forests We found that selective logging affects the abundance and species richness of gleaning and the proportional abundance of the most common species Given the absence of national parks and protected nature reserves in the continued survival of these species and other bats may largely depend on adequate protection of existing forest reserves Indeed throughout the neotropics most forest exists outside national parks and nature reserves and our study illustrates that significant biodiversity conservation efforts can occur in other types of reserves such as those set aside for sustainable development However national parks should be established'}

In [10]:
for id in tqdm(df_meta.query('discipline == "Other"').index):
    get_text_slices(id)

100%|██████████| 32277/32277 [02:46<00:00, 193.99it/s]

In [11]:
stash

LMDBHashStash(~/github/ordinary-style-philosophy/data/raw/stash/osp_slices_1000/lmdb.hashstash.lz4+b64/data.db)

In [13]:
STASH_SLICES.path

'/Users/ryan/github/ordinary-style-philosophy/data/raw/stash/osp_slices_1000/lmdb.hashstash.lz4+b64/data.db'