In [1]:
import sys
sys.path.append('..')
from osp import *
import html

In [2]:
# !pip install langdetect

In [3]:
from langdetect import detect
# detect('Bonjour!')

In [4]:
slice2lang = {}

# for slice_id, slice_docstr in tqdm(STASH_SLICES_NLP.items(), total=len(STASH_SLICES_NLP)):
#     slice_doc = stanza.Document.from_serialized(slice_docstr)
#     slice_txt = slice_doc.text
#     slice2lang[slice_id] = detect(slice_txt)

In [5]:
pd.Series(slice2lang).value_counts()

Series([], Name: count, dtype: int64)

In [6]:
df_feats = STASH_SLICE_FEATS.df

In [7]:
df_feats

,pos_DT,pos_VBZ,pos_RB,pos_JJ,pos_IN,pos_NN,pos_PRP$,pos_NNS,pos_TO,pos_VB,...,pos_LS,pos_NFP,deprel_vocative,pos_SYM,deprel_orphan,pos_AFX,pos_ADD,deprel_goeswith,pos_GW,deprel_obl:tmod
_key,,,,,,,,,,,,,,,,,,,,,
phil/10.2307/2380200__04,84.104289,46.257359,81.581161,116.904962,111.017662,102.607233,15.979815,45.416316,22.708158,58.031960,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
other/10.2307/2514892__02,87.415222,20.346647,16.578749,97.211756,143.180106,113.790505,5.275057,66.314996,5.275057,11.303693,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
other/10.2307/14710__03,102.811245,11.244980,46.586345,100.401606,130.120482,167.068273,12.048193,52.208835,8.032129,17.670683,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
phil/10.2307/20111773__02,98.193244,56.559309,56.559309,98.193244,135.113904,109.190888,6.284368,35.349568,9.426551,24.351925,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
phil/10.2307/2379466__05,91.644205,32.345013,65.588500,79.065588,139.263252,141.958670,11.680144,53.908356,12.578616,40.431267,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
lit/468421__06,116.161616,40.404040,44.612795,75.757576,136.363636,162.457912,11.784512,54.713805,14.309764,37.878788,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
other/10.2307/29782027__24,80.839895,18.372703,29.921260,51.968504,70.341207,87.664042,0.524934,25.721785,7.349081,25.721785,...,NaN,5.249344,NaN,0.524934,NaN,NaN,NaN,NaN,NaN,NaN
lit/459531__04,92.471358,40.098200,36.824877,80.196399,135.842881,134.206219,18.003273,49.099836,21.276596,32.733224,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
lit/433908__02,41.918581,8.464329,11.688835,38.694075,71.342201,84.240226,4.836759,38.291012,1.612253,10.076582,...,0.403063,NaN,5.239823,NaN,NaN,NaN,NaN,NaN,NaN,NaN
phil/10.2307/2185617__06,91.458154,56.082830,58.671268,63.848145,165.660052,148.403796,21.570319,44.003451,17.256255,38.826575,...,NaN,NaN,NaN,NaN,0.862813,NaN,NaN,NaN,NaN,NaN

In [8]:
df_feats_z = pd.DataFrame(df_feats.values, index=df_feats.index, columns=df_feats.columns)
for c in df_feats_z.columns:
    df_feats_z[c] = pd.to_numeric(df_feats_z[c], errors='coerce').fillna(0)
    df_feats_z[c] = (df_feats_z[c] - df_feats_z[c].mean()) / df_feats_z[c].std()
df_feats_z = df_feats_z.loc[[i for i in df_feats_z.index]]# if slice2lang.get(i)=='en']]
df_feats_z

,pos_DT,pos_VBZ,pos_RB,pos_JJ,pos_IN,pos_NN,pos_PRP$,pos_NNS,pos_TO,pos_VB,...,pos_LS,pos_NFP,deprel_vocative,pos_SYM,deprel_orphan,pos_AFX,pos_ADD,deprel_goeswith,pos_GW,deprel_obl:tmod
_key,,,,,,,,,,,,,,,,,,,,,
phil/10.2307/2380200__04,-0.971340,0.842103,3.045618,2.142348,-1.341446,-1.599537,0.547509,-0.159382,1.635407,2.212708,...,-0.360471,-0.227423,-0.388949,-0.199913,-0.174895,-0.145034,-0.086349,-0.01923,-0.0456,-0.005109
other/10.2307/2514892__02,-0.793884,-0.942321,-2.223544,1.108831,0.433220,-1.207474,-0.946357,0.867249,-1.367570,-1.633699,...,-0.360471,-0.227423,-0.388949,-0.199913,-0.174895,-0.145034,-0.086349,-0.01923,-0.0456,-0.005109
other/10.2307/14710__03,0.031297,-1.569136,0.208902,1.276237,-0.287387,0.660334,-0.001156,0.174295,-0.892644,-1.109605,...,-0.360471,-0.227423,-0.388949,-0.199913,-0.174895,-0.145034,-0.086349,-0.01923,-0.0456,-0.005109
phil/10.2307/20111773__02,-0.216215,1.551580,1.017321,1.160340,-0.011859,-1.368727,-0.805506,-0.653903,-0.652445,-0.559643,...,-0.360471,-0.227423,-0.388949,-0.199913,-0.174895,-0.145034,-0.086349,-0.01923,-0.0456,-0.005109
phil/10.2307/2379466__05,-0.567223,-0.116015,1.749236,0.156503,0.217095,-0.219957,-0.052517,0.257783,-0.109479,0.763918,...,-0.360471,-0.227423,-0.388949,-0.199913,-0.174895,-0.145034,-0.086349,-0.01923,-0.0456,-0.005109
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
lit/468421__06,0.746837,0.438996,0.048924,-0.017104,0.057099,0.498704,-0.037953,0.297350,0.188723,0.553812,...,-0.360471,-0.227423,-0.388949,-0.199913,-0.174895,-0.145034,-0.086349,-0.01923,-0.0456,-0.005109
other/10.2307/29782027__24,-1.146302,-1.078263,-1.141986,-1.265576,-3.585900,-2.123414,-1.609244,-1.126860,-1.010304,-0.446883,...,-0.360471,4.888631,-0.388949,0.269162,-0.174895,-0.145034,-0.086349,-0.01923,-0.0456,-0.005109
lit/459531__04,-0.522890,0.417933,-0.582372,0.215849,0.028365,-0.491742,0.829885,0.021568,1.388810,0.130259,...,-0.360471,-0.227423,-0.388949,-0.199913,-0.174895,-0.145034,-0.086349,-0.01923,-0.0456,-0.005109
lit/433908__02,-3.232368,-1.760635,-2.619925,-1.962230,-3.530667,-2.243446,-1.007522,-0.509407,-1.998514,-1.734708,...,0.118477,-0.227423,8.113293,-0.199913,-0.174895,-0.145034,-0.086349,-0.01923,-0.0456,-0.005109
phil/10.2307/2185617__06,-0.577195,1.518766,1.188519,-0.642122,1.673622,0.005996,1.327672,-0.228788,0.696278,0.631829,...,-0.360471,-0.227423,-0.388949,-0.199913,5.771150,-0.145034,-0.086349,-0.01923,-0.0456,-0.005109

In [9]:
# feats = ['deprel_cop', 'pos_MD', 'deprel_aux', 'deprel_expl']
# top_slices = df_feats_z[feats].mean(axis=1).sort_values(ascending=True)
# all_html = get_slices_html_simple(top_slices.head(50).index, df_feats_z=df_feats_z, feat_bold='deprel_cop', feat_italic='pos_MD', feat_underline={'deprel':['expl','aux']})
# with open('../data/slices_cop_md_expl_aux.html', 'w') as f:
#     f.write(all_html)

In [10]:
# feats = ['deprel_mark', 'pos_VB', 'pos_VBP', 'deprel_csubj:outer','deprel_xcomp','deprel_csubj']
# top_slices = df_feats_z[feats].mean(axis=1).sort_values(ascending=True)
# all_html = get_slices_html_simple(
#     top_slices.head(50).index, df_feats_z=df_feats_z, 
#     feat_bold='deprel_mark', feat_italic={'pos':['VB','VBP']}, feat_underline={'deprel':['csubj:outer','xcomp','csubj']}
# )
# with open('../data/REVERSED_slices_mark_vb_vbp_csubjouter_xcomp_csubj.html', 'w') as f:
#     f.write(all_html)

In [11]:
feats = ['pos_SYM','deprel_mark']
top_slices = df_feats_z.loc[[i for i in df_feats_z.index if i.startswith('phil/')]][feats].mean(axis=1).sort_values(ascending=False)
all_html = get_slices_html_simple(
    top_slices.index[:200], df_feats_z=df_feats_z, 
    # feat_bold='pos_SYM', feat_underline={'pos':['NFP','GW'],'deprel':['discourse']}, feat_italic={'pos':['AFX']}
    feat_bold='deprel_mark', feat_underline={'pos':['NFP','GW','SYM','AFX'],'deprel':['discourse']}
)
with open('../data/slices_sym_discourse_nfp_gw_afx_mark.html', 'w') as f:
    f.write(all_html)

100%|██████████| 200/200 [00:25<00:00,  7.79it/s]