In [1]:
import sys
sys.path.append('..')
from osp import *

In [ ]:
df = STASH_SLICE_FEATS.df

In [4]:
df_meta = get_corpus_metadata()
id2journal = dict(zip(df_meta.index, df_meta.journal))

df['journal'] = [id2journal.get(i.split('__')[0],'') for i in df.index]

In [17]:
pd.set_option('display.max_rows', 500)

df['law_or_phil'] = ['Law' if ' Law ' in j else ('Philosophy' if i.startswith('phil/') else 'Neither') for i,j in zip(df.index,df.journal)]

df['pos_MD'] = (df['pos_MD'] - df['pos_MD'].mean()) / df['pos_MD'].std()

In [23]:
df['deprel_mark'] = (df['deprel_mark'] - df['deprel_mark'].mean()) / df['deprel_mark'].std()

In [18]:
df.law_or_phil.value_counts()

law_or_phil
Neither       45018
Philosophy    30383
Law            1196
Name: count, dtype: int64

In [27]:
df.groupby('law_or_phil').mean(numeric_only=True)[['pos_MD','deprel_mark']]

               pos_MD  deprel_mark
law_or_phil
Law          0.332838     0.300293
Neither     -0.371455    -0.425188
Philosophy   0.533569     0.616696

In [ ]:
df.groupby('law_or_phil').mean(numeric_only=True)[['pos_MD']]

               pos_MD
deprel_mark
-2.714444         NaN
-2.713442   -1.828260
-2.713363         NaN
-2.713108         NaN
-2.713080   -1.813204
...               ...
 5.469575    1.223325
 5.592792    9.456898
 5.904686    2.503579
 6.027559    0.088373
 6.828344    0.437015

[20802 rows x 1 columns]

In [ ]:
df[df.law_or_phil == 'Law'].journal.value_counts()

journal
The Yale Law Journal                                                                                                                                                                                          116
Columbia Law Review                                                                                                                                                                                            99
Michigan Law Review                                                                                                                                                                                            97
California Law Review                                                                                                                                                                                          84
Virginia Law Review                                                                                                                                                                                            82
Harvard Law Review                                                                                                                                                                                             79
The University of Chicago Law Review                                                                                                                                                                           73
University of Pennsylvania Law Review                                                                                                                                                                          53
Stanford Law Review                                                                                                                                                                                            51
The International and Comparative Law Quarterly                                                                                                                                                                44
The Modern Law Review                                                                                                                                                                                          25
Administrative Law Review                                                                                                                                                                                      23
The Journal of Criminal Law and Criminology (1973-)                                                                                                                                                            20
The Journal of Law & Economics                                                                                                                                                                                 19
Food, Drug, Cosmetic Law Journal                                                                                                                                                                               18
Journal of the Indian Law Institute                                                                                                                                                                            17
Duke Law Journal                                                                                                                                                                                               17
Antitrust Law Journal                                                                                                                                                                                          16
The Virginia Law Register                                                                                                                                                                                      16
Mental and Physical Disability Law Reporter                                                                                                                                                                    15
The Cambridge Law Journal                                                                                                                                                                                      14
Arab Law Quarterly                                                                                                                                                                                             12
Proceedings of the American Society of International Law at Its Annual Meeting (1921-1969)                                                                                                                     12
The University of Toronto Law Journal                                                                                                                                                                          12
University of Pennsylvania Law Review and American Law Register                                                                                                                                                11
Journal of Law and Society                                                                                                                                                                                     11
Public Contract Law Journal                                                                                                                                                                                    10
Industrial Relations Law Journal                                                                                                                                                                               10
Journal of Criminal Law and Criminology (1931-1951)                                                                                                                                                            10
Tort & Insurance Law Journal                                                                                                                                                                                    8
Ecology Law Quarterly                                                                                                                                                                                           8
The American Law Register (1898-1907)                                                                                                                                                                           8
Fordham Environmental Law Review                                                                                                                                                                                8
The Comparative and International Law Journal of Southern Africa                                                                                                                                                7
Malaya Law Review                                                                                                                                                                                               7
American Indian Law Review                                                                                                                                                                                      6
Virginia Environmental Law Journal                                                                                                                                                                              6
Journal of Law and Religion                                                                                                                                                                                     5
Family Law Quarterly                                                                                                                                                                                            5
New Criminal Law Review: An International and Interdisciplinary Journal                                                                                                                                         5
Franchise Law Journal                                                                                                                                                                                           4
UCLA Journal of International Law and Foreign Affairs                                                                                                                                                           4
Food, Drug, Cosmetic Law Quarterly                                                                                                                                                                              4
Tulane Environmental Law Journal                                                                                                                                                                                4
European State Aid Law Quarterly                                                                                                                                                                                3
Tort Trial & Insurance Practice Law Journal                                                                                                                                                                     3
High Technology Law Journal                                                                                                                                                                                     3
Food and Drug Law Journal                                                                                                                                                                                       3
Business Law Today                                                                                                                                                                                              3
The International Law Quarterly                                                                                                                                                                                 3
British Journal of Law and Society                                                                                                                                                                              3
The University of Miami Inter-American Law Review                                                                                                                                                               3
Chicanx-Latinx Law Review                                                                                                                                                                                       2
Australian Indigenous Law Reporter                                                                                                                                                                              2
KritV, CritQ, RCrit. Kritische Vierteljahresschrift für Gesetzgebung und Rechtswissenschaft / Critical Quarterly for Legislation and Law / Revue critique trimestrielle de jurisprudence et de législation      2
Verfassung und Recht in Übersee / Law and Politics in Africa, Asia and Latin America                                                                                                                            2
Real Property, Trust and Estate Law Journal                                                                                                                                                                     2
Yale Law & Policy Review                                                                                                                                                                                        1
Australian Indigenous Law Review                                                                                                                                                                                1
Section of International and Comparative Law Bulletin                                                                                                                                                           1
Arctic Review on Law and Politics                                                                                                                                                                               1
Islamic Law and Society                                                                                                                                                                                         1
Asian Pacific American Law Journal                                                                                                                                                                              1
European Procurement & Public Private Partnership Law Review                                                                                                                                                    1
Name: count, dtype: int64