In [1]:
# !pip install -q hashstash[rec] stanza
import sys
sys.path.append('..')
from osp import *

In [2]:
get_nlp()

In [3]:
# !unzip -n osp_slices_1000.zip
# !mkdir -p /root/.cache/hashstash
# !rm -rf /root/.cache/hashstash/osp_slices_1000
# !mv osp_slices_1000 /root/.cache/hashstash

In [4]:
input_stash = STASH_SLICES
input_stash

LMDBHashStash(~/github/ordinary-style-philosophy/data/raw/stash/osp_slices_1000/lmdb.hashstash.lz4+b64/data.db)

In [5]:
output_stash = STASH_SLICES_NLP
output_stash

LMDBHashStash(~/github/ordinary-style-philosophy/data/raw/stash/osp_slices_1000_nlp/lmdb.hashstash.lz4+b64/data.db)

In [6]:
def get_slice_key(text_id, slice_id):
    return f'{text_id}__{int(slice_id):02d}'

In [7]:
slices_by_period = defaultdict(list)
df_meta = get_corpus_metadata()

for text_id,row in tqdm(list(df_meta.query('discipline=="Other"').iterrows())):
    text_slices = get_text_slices(text_id)
    for slice_id, slice_txt in text_slices.items():
        slices_by_period[row.period].append((get_slice_key(text_id, slice_id), slice_txt))

for k in slices_by_period:
    print(k, len(slices_by_period[k]))

100%|██████████| 32277/32277 [00:02<00:00, 15221.78it/s]

1975-2000 10373
2000-2025 15402
1950-1975 6679
1925-1950 3966
1900-1925 1587

In [8]:
inps = [x for k,v in slices_by_period.items() for x in random.sample(v,1000)]
len(inps)

5000

In [9]:
inps[0]

('other/10.2307/524189__01',
 "The Functioning and Effects of the Kenya Literacy Program G. Carron Background Over the last few decades, an increasing number of developing countries have embarked upon the organization of nationwide literacy programs.\nAlthough the rationale behind those programs varies from country to country, it is generally expected that efforts to increase the literacy levels of adults will have positive consequences for both the learners and the nation as a whole.\nIt is worth noting, however, that until now empirical evidence which could support these expectations has remained extremely weak.\nBy and large, adult literacy has been a neglected area in terms of data collection and research.\nIn many countries it may even be difficult to find precise information about simple facts such as the number of adults enrolled in literacy classes, the number of instructors, or the number of literacy proficiency certificates which have been delivered.\nIn most cases the illiteracy rate, which is an essential indicator for any plan of action in the field of literacy, is only a crude measure based on self reporting by household heads and on questionable assumptions about the equivalency between a given number of years of primary school attendance and a sufficient proficiency level in reading and writing.\nIt can be seen from the list of objectives that the question of impact of the literacy program on the lives of the participants and on their communities is not being dealt with explicitly.\nThis would have necessitated a different research design and would have required the mobilization of resources which were beyond the capacity of the research project.\nResearch Design and Implementation The basic methodological assumption behind the research design is that the real issues involved in the functioning and effects of literacy classes can be best understood when these classes are analyzed within their local settings.\nFor this reason, a micro-approach was adopted.\nFive local communities which represent contrasting development contexts and living conditions ranging from an urban zone to a remote rural area were selected.\nThis purposeful selection of areas and of all the literacy centers in each of them does not claim to be representative nationwide.\nThe local level which has been chosen for the purpose of this project is the location.\nIn Kenya the location is the second smallest administrative unit of a district.\nIt offers the advantage of having a manageable size without being too small.\nIt is headed by a chief and constitutes, at least in the rural areas, a real social entity.\nHowever, during the field work it was realized that the number of people that could actually be reached for interviewing was less than originally expected (which confirms the high degree of mobility of Kenyan society).\nThere were no refusals to take the interview as such.\nThe fact that fewer people were tested than interviewed is no surprise.\nThe learners were visited in their homes for the interviews while the test had to be taken collectively in one of the literacy centers later on.\nLearners were kindly invited to take the test, but no pressure was put on them.\nConsequently, many literates who had been interviewed did not take the test while some who for one reason or another had not been interviewed did nevertheless sit for the test.\nAlthough one could make the assumption that those who turned up for the test felt more confident about their literacy skills than those who did not, it would be difficult to say much more about the possible bias introduced by the incomplete coverage of the real sample.\nThe information concerning the characteristics and the functioning of the literacy centers was collected from the literacy teachers who were interviewed in their respective classes.\nThis gave the interviewers an opportunity to do some complementary observation and to check on the availability of the various types of equipments, registers, and records in specific literacy centers.\nThis will be done by analyzing successively the functioning of the literacy classes, the characteristics of the adult learners, their motivation and learning experience, and, finally, some of the effects of the literacy program.\nThe Functioning of the Literacy Classes Analysis of the data collected shows that the first problem which the Kenyan literacy program is facing is its limited coverage and the difficulty of sustaining its growth.\nThe decline of enrollments has been the result not of a reduction of the supply, but of a rapid demobilization of the demand.\nThe central issue, therefore, is the motivation of the learner.\nIt determines the learner's decision to enroll, regularity of attendance, and perseverance to continue.\nIt also influences the learner's final performance level.\nAt the beginning of the campaign, massive efforts were made at all levels of society to encourage adults to enroll in the literacy classes and to continue attending them.\nBut those efforts could not be maintained with the same degree of intensity over a long period.\nMass mobilization can give an initial push to overcome certain inhibitions which deter people from enrolling, but it cannot in the long run compensate for the objective realities which make regular participation difficult.\nThese realities relate not only to the specific living conditions of the learner, which are largely beyond the control of the organizers of the literacy program, but also to the quality of the literacy services that are being offered.\nAccording to the observations made during field visits, the teaching/learning conditions in terms of facilities and availability of various types of equipment and material were rather good in general.\nIt was observed that such open air classrooms take place under dusty, sunny, or windy conditions, none of which are particularly suitable for good learning.\nThe basic equipment for teachers, such as blackboards, chalk, and teachers' manuals, are available in nearly all the classes.\nHowever, the most critical input for a successful teaching process is the teacher.\nThere are three categories of adult literacy teachers in Kenya: full-time, part-time and self-help.\nFull-time teachers are civil servants and are expected to spend five full working days in functions related to adult literacy teaching (even though in most cases only two hours a day are spent in actual teaching).")

In [10]:
import random
random.shuffle(inps)

In [11]:
def gen_nlp_doc(txt, key, force=False, stash=output_stash):
    if force or key not in stash:
        nlp = get_nlp()
        doc = nlp(txt)
        stash[key] = doc.to_serialized()
        return doc

In [12]:
for key, txt in tqdm(inps):
    gen_nlp_doc(txt, key)

 10%|▉         | 497/5000 [39:58<6:02:08,  4.83s/it]

KeyboardInterrupt: